### ISSUE TITLE
KeyError in CandidateForGraceDB

### ISSUE THREAD

**Issue by titodalcanton** [gwastro/pycbc#4189]
The MDC analysis died a couple times earlier today with this error:
```
[…]
2022-11-23T18:58:22.683-08:00 node836 0 Adding V1 to candidate, pvalue 0.00029770765108663293, 3358 samples
2022-11-23T18:58:22.689-08:00 node836 0 Generating SPAtmplt, 288.0s, 14046, starting from 25.1 Hz
2022-11-23T18:58:22.848-08:00 node836 0 Adding L1 to candidate, pvalue 0.00013757050488375291, 7268 samples
2022-11-23T18:58:22.879-08:00 node836 0 Computing p_astro
2022-11-23T18:58:22.955-08:00 node836 0 Single-detector candidate! Saving as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/single-H1-1353293905.746582-qmgttr.xml.gz
2022-11-23T18:58:22.955-08:00 node836 0 Single-detector candidate at time 1353293905.747 was already reported as coinc, skipping upload
2022-11-23T18:58:23.080-08:00 node836 0 Multi p_astro file saved as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/single-H1-1353293905.746582-qmgttr_p_astro.json
2022-11-23T18:58:23.083-08:00 node836 0 Found L1 single with ifar 450.1521972642238
2022-11-23T18:58:23.084-08:00 node836 0 Generating SPAtmplt, 80.0s, 409061, starting from 25.1 Hz
2022-11-23T18:58:23.139-08:00 node836 0 Generating SPAtmplt, 288.0s, 409061, starting from 25.1 Hz
2022-11-23T18:58:23.523-08:00 node836 0 Adding V1 to candidate, pvalue 0.00028876696505919725, 3462 samples
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 1017, in <module>
    evnt.check_singles(results, psds)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 469, in check_singles
    event = CandidateForGraceDB(
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/pycbc/io/live.py", line 181, in __init__
    [coinc_results[f'foreground/{ifo}/end_time'] for ifo in ifos]) \
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/pycbc/io/live.py", line 181, in <listcomp>
    [coinc_results[f'foreground/{ifo}/end_time'] for ifo in ifos]) \
KeyError: 'foreground/H1/end_time'
```
It feels related to the various changes in #4159. @tdent could you take a look?

**Comment by tdent** [comment]
Was it in check_singles both times?

**Comment by titodalcanton** [comment]
Good point, no, the second one is this:
```
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 1013, in <module>
    evnt.check_coincs(list(results.keys()), best_coinc, psds)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 384, in check_coincs
    event = CandidateForGraceDB(
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/pycbc/io/live.py", line 181, in __init__
    [coinc_results[f'foreground/{ifo}/end_time'] for ifo in ifos]) \
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/pycbc/io/live.py", line 181, in <listcomp>
    [coinc_results[f'foreground/{ifo}/end_time'] for ifo in ifos]) \
KeyError: 'foreground/V1/end_time'
```

**Comment by tdent** [comment]
It could be removing the line `live_ifos = [i for i in fud if 'snr_series' in fud[i]]` which may have been catching a corner case of the followup SNR time series calculation .. ie the new code may be implicitly making an assumption about which ifos will get time series with trigger times

**Comment by tdent** [comment]
I.e. in the second case we would want V1 to have a ts with an end time identified, but for whatever reason it didn't get one ..

**Comment by titodalcanton** [comment]
I think the problem is actually here:
```
        # Set merger time to the mean of trigger peaks over coinc_results ifos
        self.merger_time = numpy.mean(
            [coinc_results[f'foreground/{ifo}/end_time'] for ifo in ifos]) \
            + self.time_offset
```
What the comment describes seems the right approach, but that is not what the code does!

**Comment by titodalcanton** [comment]
And I think a similar problem is in multiple places in the constructor of CandidateForGraceDB now. The code is assuming that every detector listed in `ifos` will have an entry in `coinc_results`, which is clearly not the case.

**Comment by tdent** [comment]
You mean in the inputs given to it on initialization or in the __init__ method itself?

**Comment by tdent** [comment]
Hopefully fixed now?

**Comment by titodalcanton** [comment]
This is unfortunately not fixed yet. From the MDC analysis:
```
2022-12-13T15:58:51.227-08:00 node836 0 Found V1-L1 coinc with ifar 0.012470689506309042
2022-12-13T15:58:51.227-08:00 node836 0 computing followup data for coinc
2022-12-13T15:58:51.228-08:00 node836 0 Generating SPAtmplt, 96.0s, 7107, starting from 25.1 Hz
2022-12-13T15:58:51.384-08:00 node836 0 Computing p_astro
2022-12-13T15:58:51.453-08:00 node836 0 Coincident candidate! Saving as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355011132.2861328-tadjka.xml.g
z
2022-12-13T15:58:51.524-08:00 node836 0 Multi p_astro file saved as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355011132.2861328-tadjka_p_astro.j
son
2022-12-13T15:58:53.440-08:00 node836 0 Uploaded event G805524
2022-12-13T15:59:00.472-08:00 node836 0 Uploaded multi p_astro for G805524
2022-12-13T15:59:00.473-08:00 node836 0 Optimizing SNR for coinc above threshold ..
2022-12-13T15:59:00.643-08:00 node836 0 running timeout 400 /home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_optimize_snr --data-files V1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355011132.2861328-tadjka_V1_data_overwhitened.hdf L1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-135501113
2.2861328-tadjka_L1_data_overwhitened.hdf --psd-files V1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355011132.2861328-tadjka_V1_psd.hdf L1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355011132.2861328-tadjka_L1_psd.hdf --params-file /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc
-1355011132.2861328-tadjka_attributes.hdf --approximant SPAtmplt --gracedb-server https://gracedb-playground.ligo.org/api/ --gracedb-search AllSky --production --verbose --output-path /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers --enable-gracedb-upload --cores 20 --processing-scheme cpu:1  with log to /local/pycbc.
live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355011132.2861328-tadjka_optimize_snr.log
2022-12-13T15:59:01.300-08:00 node836 0 Found V1 single with ifar 0.19117560697540256
2022-12-13T15:59:01.302-08:00 node836 0 Generating SPAtmplt, 96.0s, 339637, starting from 25.1 Hz
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 1032, in <module>
    evnt.check_singles(results, psds)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 469, in check_singles
    event = CandidateForGraceDB(
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/pycbc/io/live.py", line 63, in __init__
    self.template_id = coinc_results[f'foreground/{ifos[0]}/template_id']
KeyError: 'foreground/L1/template_id'
```
and soon after,
```
2022-12-13T16:26:16.433-08:00 node836 0 Found H1-L1 coinc with ifar 0.013952898826273227
2022-12-13T16:26:16.434-08:00 node836 0 computing followup data for coinc
2022-12-13T16:26:16.434-08:00 node836 0 Generating SPAtmplt, 72.0s, 11192, starting from 25.1 Hz
2022-12-13T16:26:16.730-08:00 node836 0 Generating SPAtmplt, 264.0s, 11192, starting from 25.1 Hz
2022-12-13T16:26:17.426-08:00 node836 0 Adding V1 to candidate, pvalue 0.9621101719615273, 3430 samples
2022-12-13T16:26:17.455-08:00 node836 0 Computing p_astro
2022-12-13T16:26:17.528-08:00 node836 0 Coincident candidate! Saving as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery.xml.gz
2022-12-13T16:26:17.639-08:00 node836 0 Multi p_astro file saved as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_p_astro.json
2022-12-13T16:26:18.694-08:00 node836 0 Uploaded event G805539
2022-12-13T16:26:25.824-08:00 node836 0 Uploaded multi p_astro for G805539
2022-12-13T16:26:25.824-08:00 node836 0 Optimizing SNR for coinc above threshold ..
2022-12-13T16:26:25.972-08:00 node836 0 running timeout 400 /home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_optimize_snr --data-files H1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_H1_data_overwhitened.hdf L1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_L1_data_overwhitened.hdf V1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_V1_data_overwhitened.hdf --psd-files H1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_H1_psd.hdf L1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_L1_psd.hdf V1:/local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_V1_psd.hdf --params-file /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_attributes.hdf --approximant SPAtmplt --gracedb-server https://gracedb-playground.ligo.org/api/ --gracedb-search AllSky --production --verbose --output-path /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers --enable-gracedb-upload --cores 20 --processing-scheme cpu:1  with log to /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/coinc-1355012781.838216-tspery_optimize_snr.log
2022-12-13T16:26:25.993-08:00 node836 0 Found H1 single with ifar 1.6119239952801467
2022-12-13T16:26:25.994-08:00 node836 0 Generating SPAtmplt, 72.0s, 11193, starting from 25.1 Hz
2022-12-13T16:26:26.033-08:00 node836 0 Generating SPAtmplt, 264.0s, 11193, starting from 25.1 Hz
2022-12-13T16:26:26.276-08:00 node836 0 Adding V1 to candidate, pvalue 0.8801639861242511, 3170 samples
2022-12-13T16:26:26.281-08:00 node836 0 Generating SPAtmplt, 264.0s, 11193, starting from 25.1 Hz
2022-12-13T16:26:26.437-08:00 node836 0 Adding L1 to candidate, pvalue 0.0001457301078402798, 6861 samples
2022-12-13T16:26:26.466-08:00 node836 0 Computing p_astro
2022-12-13T16:26:26.537-08:00 node836 0 Single-detector candidate! Saving as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/single-H1-1355012781.833659-bpwfio.xml.gz
2022-12-13T16:26:26.537-08:00 node836 0 Single-detector candidate at time 1355012781.834 was already reported as coinc, skipping upload
2022-12-13T16:26:26.650-08:00 node836 0 Multi p_astro file saved as /local/pycbc.live/pre_O4_mdc/full_bandwidth/triggers/single-H1-1355012781.833659-bpwfio_p_astro.json
2022-12-13T16:26:26.653-08:00 node836 0 Found L1 single with ifar 1.158691737145311
2022-12-13T16:26:26.654-08:00 node836 0 Generating SPAtmplt, 72.0s, 11192, starting from 25.1 Hz
2022-12-13T16:26:26.693-08:00 node836 0 Generating SPAtmplt, 264.0s, 11192, starting from 25.1 Hz
2022-12-13T16:26:26.922-08:00 node836 0 Adding V1 to candidate, pvalue 0.9663608562691132, 3269 samples
Traceback (most recent call last):
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 1032, in <module>
    evnt.check_singles(results, psds)
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/bin/pycbc_live", line 469, in check_singles
    event = CandidateForGraceDB(
  File "/home/pycbc.live/.conda/envs/pre-o4-mdc-env/lib/python3.9/site-packages/pycbc/io/live.py", line 63, in __init__
    self.template_id = coinc_results[f'foreground/{ifos[0]}/template_id']
KeyError: 'foreground/H1/template_id'
```

**Comment by tdent** [comment]
Should be addressed by https://github.com/gwastro/pycbc/pull/4211
